---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: microservice2-svc
  name: microservice2-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: microservice2-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: microservice2-svc
    spec:
      containers:
      - name: microservice2-svc
        image: docker.io/gzapataz/microservice2
        imagePullPolicy: IfNotPresent
        env:
          - name: API_QUEUE
            value: "192.168.50.4"
        ports:
        - containerPort: 3020
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: microservice2-svc
  name: microservice2-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3020
  selector:
    run: microservice2-svc
  sessionAffinity: None
  type: LoadBalancer
